Repository neolink78/Editoria, pull requests merged in 2024-04, with the labels that each got.

#48 Initialization of graphQL codeGen in frontend
  front/gql/fragment-masking.ts
  front/gql/gql.ts
  front/gql/graphql.ts
  front/gql/index.ts
  front/graphql-codegen.ts
  front/package-lock.json
  front/package.json
  front/pages/_app.tsx
  front/pages/apollo-client.ts
Labels: Frontend

#43 Add Fav coders part of account page
  front/components/user/fav.tsx
  front/pages/user/account.tsx
Labels: Frontend

#44 Add user property for tiles to display user
  front/components/user/dashboard.tsx
  front/lib/tile.tsx
  front/mocks/indexMock.tsx
  front/pages/index.tsx
Labels: Frontend

#51 Add field to projects/codesnippet relation
  back/src/entities/project/project.ts
Labels: Backend

#53 Dashboard projects
  back/src/entities/codeSnippet/codeSnippet.ts
  back/src/entities/project/project.ts
  front/components/layout.tsx
  front/components/user/dashboard.tsx
  front/components/user/dashboardProjects.tsx
  front/components/user/fav.tsx
  front/context/ModalContext.tsx
  front/gql/gql.ts
  front/gql/graphql.ts
  front/icons/arrowLeftIcon.tsx
  front/icons/arrowRightIcon.tsx
  front/lib/modal.tsx
  front/lib/tile.tsx
  front/package-lock.json
  front/package.json
  front/pages/_app.tsx
Labels: Frontend

#57 Feat/sign in sign out pages
  back/.DS_Store
  back/package-lock.json
  back/package.json
  back/src/database.ts
  back/src/entities/user/user.args.ts
  back/src/entities/user/user.ts
  back/src/entities/user/userResetSession.ts
  back/src/resolvers/ProjectResolver.ts
  back/src/resolvers/UserResolver.ts
  back/src/utils/cookie.ts
  front/apollo-client.ts
  front/components/input.tsx
  front/components/layout.tsx
  front/components/tile.tsx
  front/gql/gql.ts
  front/gql/graphql.ts
  front/graphql-codegen.ts
  front/hooks/form.tsx
  front/hooks/formReset.tsx
  front/lib/submitButton.tsx
  front/package-lock.json
  front/package.json
  front/pages/_app.tsx
  front/pages/reset/email.tsx
  front/pages/reset/password.tsx
  front/pages/sign-in.tsx
  front/pages/sign-up.tsx
  front/styles/globals.css
  front/styles/header.css
  front/styles/sign-pages.css
  front/styles/submitButton.css
Labels: Frontend, Backend
